behaviors:
  DrunkAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 4096
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 8
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
      gail:
        strength: 0.5
        demo_path: config\DrunkAgentDemo.demo
    behavioral_cloning:
        strength: 0.5
        demo_path: config\DrunkAgentDemo.demo
    keep_checkpoints: 5
    max_steps: 500000000
    time_horizon: 64
    summary_freq: 10000
    threaded: true